@startuml
activate Main
Main -> Engine : newEngine("Petrol", 2000)
activate Engine
Engine --> Main : Engine
deactivate Engine
Main -> Car : newCar("Toyota", 2015, "Corolla", engine1)
activate Car
Car --> Main : Car
deactivate Car
Main -> Engine : newEngine("Diesel", 2500)
activate Engine
Engine --> Main : Engine
deactivate Engine
Main -> Car : newCar("Ford", 2020, "Mustang", engine2)
activate Car
Car --> Main : Car
deactivate Car
Main -> Person : newPerson("John")
activate Person
Person --> Main : Person
deactivate Person
Main -> Person : addCar(car1)
activate Person
Person --> Main : void
deactivate Person
Main -> Person : addCar(car2)
activate Person
Person --> Main : void
deactivate Person
loop
Main -> Car : getManufacturer()
activate Car
Car --> Main : String
deactivate Car
end
alt person.getCars().size()>0
Main -> Person : calculateInsuranceFee()
activate Person
Person --> Main : double
deactivate Person
else person.getCars().size() == 0
Main -> Car : getManufacturer()
activate Car
Car --> Main : String
deactivate Car
else other condition
Main -> Car : getManufacturer()
activate Car
Car --> Main : String
deactivate Car
end
loop
Main -> Car : getEngine()
activate Car
Car --> Main : Engine
deactivate Car
end
deactivate Main
@enduml